import type { Match, Patch, ModelStat } from './types';

// 6月5日 12场 A级成年男子国际赛（12场含 8场预测 + 4场主动放弃）
export const matches6_5: Match[] = [
  {
    id: "esp-irq",
    date: "2026-06-05",
    time: "03:00",
    league: "国际友谊",
    home: "西班牙",
    away: "伊拉克",
    homeIcon: "ESP",
    awayIcon: "IRQ",
    status: "finished",
    score: { home: 1, away: 1 },
    prediction: {
      direction: "西班牙胜",
      confidence: 4,
      asian: "让球放弃",
      overUnder: "大球",
      goals: "2-3球",
    },
    actual: { directionHit: false, asianHit: null, goalsHit: true },
    highlight: true,
    liveWarning: "★★★★ FIFA #2 vs #57 · 身价60倍 · 西班牙大面积轮换（亚马尔/尼科/拉亚伤缺）· 跨大洲-1档 · 反对：轮换+草皮差 · ❌ 1-1 伊拉克萨阿德32'破门 奥尔莫90'绝平 · 草皮+轮换反对论点全部命中 · 模型应降至★★",
  },
  {
    id: "fra-civ",
    date: "2026-06-05",
    time: "03:10",
    league: "国际友谊",
    home: "法国",
    away: "科特迪瓦",
    homeIcon: "FRA",
    awayIcon: "CIV",
    status: "finished",
    score: { home: 1, away: 2 },
    prediction: {
      direction: "法国胜",
      confidence: 4,
      asian: "让球降权",
      overUnder: "大球",
      goals: "2-3球",
    },
    actual: { directionHit: false, asianHit: null, goalsHit: true },
    highlight: true,
    liveWarning: "★★★★ FIFA #1 vs #34 · 萨利巴/登贝莱/巴尔科拉轮休 · 姆巴佩追平吉鲁57球 · 跨大洲-1档 · 反对：法科青训内战 · ❌ 1-2 法国队史首次输科特迪瓦 · 谢尔基45'破门后塞拉-杜埃+迪亚洛反超 · 客队3大归化核心决定性",
  },
  {
    id: "ber-biz",
    date: "2026-06-05",
    time: "06:00",
    league: "中北美金杯预选",
    home: "百慕大群岛",
    away: "伯利兹",
    homeIcon: "BER",
    awayIcon: "BIZ",
    status: "pending",  // 6/5 完赛但数据延迟 48+ 小时未拉到
    score: { home: 0, away: 0 },
    prediction: {
      direction: "主动放弃",
      confidence: 1,
      asian: "弱弱放弃",
      overUnder: "N/A",
      goals: "N/A",
    },
    actual: { directionHit: null, asianHit: null, goalsHit: null, note: '完赛·比分未拉到（球迷屋/捷报指数延迟）' },
    liveWarning: "★ FIFA 48 vs 69 · 双方近期胜率<30% · Q2弱弱对决",
  },
];

// 6月6日 6场 A级成年男子国际赛（5场友谊赛+1场世预赛）
export const matches6_6: Match[] = [
  {
    id: "den-swe",
    date: "2026-06-06",
    time: "01:00",
    league: "国际友谊",
    home: "丹麦",
    away: "瑞典",
    homeIcon: "DEN",
    awayIcon: "SWE",
    status: "pending",  // 6/6 完赛·比分未在搜索引擎拉到
    score: { home: 0, away: 0 },
    prediction: {
      direction: "丹麦胜",
      confidence: 3,
      asian: "让球降权",
      overUnder: "小球",
      goals: "2-3球",
    },
    actual: { directionHit: null, asianHit: null, goalsHit: null, note: '完赛·比分未拉到' },
    liveWarning: "★★★ FIFA 21 vs 27 · 身价1.3倍 · 北欧内战 · 瑞典客场7成负 · 反对：4主力伤停+友谊赛无战意",
  },
  {
    id: "can-irl",
    date: "2026-06-06",
    time: "07:30",
    league: "国际友谊",
    home: "加拿大",
    away: "爱尔兰",
    homeIcon: "CAN",
    awayIcon: "IRL",
    status: "pending",  // 6/6 完赛·比分未在搜索引擎拉到
    score: { home: 0, away: 0 },
    prediction: {
      direction: "加拿大胜",
      confidence: 3,
      asian: "让球放弃",
      overUnder: "小球",
      goals: "2-3球",
    },
    actual: { directionHit: null, asianHit: null, goalsHit: null, note: '完赛·比分未拉到' },
    liveWarning: "★★★ FIFA 30 vs 60 · 身价1.7倍 · 已晋级2026世界杯vs欧附加赛淘汰 · 反对：友谊赛无战意",
  },
  {
    id: "chn-tha",
    date: "2026-06-06",
    time: "20:00",
    league: "世预赛亚洲区36强赛C组",
    home: "中国",
    away: "泰国",
    homeIcon: "CHN",
    awayIcon: "THA",
    status: "finished",
    score: { home: 1, away: 1 },
    prediction: {
      direction: "中国胜",
      confidence: 3,
      asian: "让球降权",
      overUnder: "大球",
      goals: "3-4球",
    },
    actual: { directionHit: false, asianHit: null, goalsHit: false, note: '**重大失败**·阿兰中柱+费南多失点+拜合拉木扳平·4条反对论点命中' },
    highlight: true,
    liveWarning: "★★★★ FIFA 79 vs 93 · 沈阳福地 6万主场 · 赢球即出线18强赛 · 反对：伊万指挥+林良铭停赛+武磊伤疑+湿热抵消主场（命中3条-1星降至3★）",
  },
  {
    id: "por-chi",
    date: "2026-06-06",
    time: "21:00",
    league: "国际友谊",
    home: "葡萄牙",
    away: "智利",
    homeIcon: "POR",
    awayIcon: "CHI",
    status: "finished",
    score: { home: 2, away: 1 },
    prediction: {
      direction: "葡萄牙胜",
      confidence: 4,
      asian: "让球降权",
      overUnder: "大球",
      goals: "3-4球",
    },
    actual: { directionHit: true, asianHit: null, goalsHit: true, note: '✅ 方向+进球·格德斯58\'+B费75\'世界波+塞佩达90+2\'·莱奥+罗曼互殴染红' },
    highlight: true,
    liveWarning: "★★★★ FIFA 5 vs 23 · 身价5.5倍 · C罗告别赛 · 智利3主力伤退 · 反对：B席+奥塔维奥+雷纳托3中场伤停",
  },
  {
    id: "svk-mne",
    date: "2026-06-06",
    time: "23:00",
    league: "国际友谊",
    home: "斯洛伐克",
    away: "黑山",
    homeIcon: "SVK",
    awayIcon: "MNE",
    status: "finished",
    score: { home: 2, away: 2 },
    prediction: {
      direction: "主动放弃",
      confidence: 1,
      asian: "弱弱放弃",
      overUnder: "N/A",
      goals: "N/A",
    },
    actual: { directionHit: null, asianHit: null, goalsHit: null, note: '主动放弃场·2-2 博热尼克+杜达·不计算预测' },
    liveWarning: "★ FIFA 48 vs 69 · 双方近期胜率<30% · Q2弱弱对决",
  },
  {
    id: "bel-tun",
    date: "2026-06-06",
    time: "21:00",
    league: "国际友谊",
    home: "比利时",
    away: "突尼斯",
    homeIcon: "BEL",
    awayIcon: "TUN",
    status: "finished",
    score: { home: 5, away: 0 },
    prediction: {
      direction: "比利时胜",
      confidence: 4,
      asian: "让球降权",
      overUnder: "大球",
      goals: "2-3球",
    },
    actual: { directionHit: true, asianHit: null, goalsHit: false, note: '✅ 方向命中·特罗萨德28\'+德凯特拉雷53\'+德布劳内65\'+卢克巴基奥85\'+拉斯金87\'·但 5 球超 2-3 球上沿' },
    liveWarning: "★★★★ FIFA 9 vs 44 · 身价7.5倍 · 比利时近12场8胜4平 · 反对：德布劳内+卢卡库伤情控制上场时间",
  },
];

// 6月6日 战报（12 场 A 级成年男子国际赛 / 6 场已完赛 6 场数据延迟 / 1 场重大失败）
export const report6_6 = {
  date: '2026-06-06',
  matchesTotal: 12,
  matchesFinished: 6,
  matchesPending: 6,
  results: [
    { id: 'svk-mne', actual: '2-2', directionHit: null, asianHit: null, goalsHit: null, note: '主动放弃场·2-2 博热尼克+杜达·不计算' },
    { id: 'chn-tha', actual: '1-1', directionHit: false, asianHit: null, goalsHit: false, note: '**重大失败**·阿兰中柱+费南多失点+拜合拉木扳平·4条反对论点命中' },
    { id: 'hun-fin', actual: '2-0', directionHit: true, asianHit: null, goalsHit: null, note: '沃尔高双响·2-0 完胜' },
    { id: 'rus-bfa', actual: '3-0', directionHit: true, asianHit: null, goalsHit: null, note: '3-0 大胜' },
    { id: 'por-chi', actual: '2-1', directionHit: true, asianHit: null, goalsHit: true, note: '✅ 方向+进球·格德斯58\'+B费75\'世界波+塞佩达90+2\'·莱奥+罗曼互殴染红' },
    { id: 'bel-tun', actual: '5-0', directionHit: true, asianHit: null, goalsHit: false, note: '✅ 方向命中·特罗萨德28\'+德凯特拉雷53\'+德布劳内65\'+卢克巴基奥85\'+拉斯金87\'·但 5 球超 2-3 球上沿' },
  ],
  pending: ['den-swe', 'can-irl', 'par-nca', 'pur-sau', 'hai-per'],
  pending5_5: ['ina-omn', 'jam-rsa', 'hkg-mng', 'ner-mtn', 'tjk-ind'],  // 6/5 5 场数据延迟 48+ 小时
  summary: '方向 4/5=80% · 让球 0/1=0% · 进球 1/5=20% · 主动放弃 0/4=0% · **中国 1-1 泰国重大失败**',
  majorLesson: '**补丁M拆分**：M1世预赛必赢战意1-2球 / M2友谊赛放松3-4球 / M3友谊赛无战意2-3球',
  focus: '中国 1-1 泰国·末轮客场对韩国必须不败才能晋级 18 强赛·补丁 L 强化（≥2条反对论点 -2 星）',
  activePatches: ['L 反对论点强制扣星', 'P 友谊赛3-4球', 'M1世预赛必赢1-2球', 'M2友谊赛放松3-4球', 'K 跨大洲-1档'],
  fullReportPath: '/skills/football-prediction/outputs/2026-06-07/pred_20260607.md',
};

// 6月7日 5场 A级成年男子国际赛（1场世预赛+4场友谊赛）
export const matches6_7: Match[] = [
  {
    id: "usa-ger",
    date: "2026-06-07",
    time: "02:30",
    league: "国际友谊",
    home: "美国",
    away: "德国",
    homeIcon: "USA",
    awayIcon: "GER",
    status: "finished",
    score: { home: 1, away: 2 },
    prediction: {
      direction: "德国胜",
      confidence: 3,
      asian: "让球放弃",
      overUnder: "大球",
      goals: "3-4球",
    },
    actual: { directionHit: true, asianHit: null, goalsHit: true, note: '✅ 方向+进球全中·哈弗茨2\'头球+萨内57\'/罗宾逊37\'世界波扳平' },
    highlight: true,
    liveWarning: "★★★ FIFA 16 vs 5 · 身价2.7倍 · 德国8连胜 · 反对：①美国大球倾向 ②德国8连胜场均3球 ③维尔茨+穆西亚拉vs美国残阵 ④德国客战8胜1负（4条-1星=3★）",
  },
  {
    id: "mkd-bel",
    date: "2026-06-07",
    time: "02:45",
    league: "世预赛欧洲区J组",
    home: "北马其顿",
    away: "比利时",
    homeIcon: "MKD",
    awayIcon: "BEL",
    status: "finished",
    score: { home: 1, away: 1 },
    prediction: {
      direction: "比利时胜",
      confidence: 3,
      asian: "让球放弃",
      overUnder: "小球",
      goals: "2-3球",
    },
    actual: { directionHit: false, asianHit: null, goalsHit: true, note: '❌ 方向反·86分钟阿利奥斯基世界波绝平·进球2球命中·补丁L命中-1星应降★★' },
    highlight: true,
    liveWarning: "★★★ FIFA 67 vs 8 · 身价8.6倍 · 北马主场8场6胜2平 6场仅失1球 · 反对：①670米高海拔+硬质草皮 ②比利时近10场2胜2平6负 ③客场3平3负6场不胜 ④北马主场6场仅失1球（4条-1星=3★）",
  },
  {
    id: "eng-nzl",
    date: "2026-06-07",
    time: "04:00",
    league: "国际友谊",
    home: "英格兰",
    away: "新西兰",
    homeIcon: "ENG",
    awayIcon: "NZL",
    status: "finished",
    score: { home: 1, away: 0 },
    prediction: {
      direction: "英格兰胜",
      confidence: 4,
      asian: "让球放弃",
      overUnder: "大球",
      goals: "3-4球",
    },
    actual: { directionHit: true, asianHit: null, goalsHit: false, note: '✅ 方向命中·凯恩45+2\'头球后蹭破门·恩古莫哈首秀·但1球未达3-4球上沿' },
    liveWarning: "★★★★ FIFA 4 vs 85 · 身价40倍 · 图赫尔首战 · 反对：近1场友谊赛0-1日本",
  },
  {
    id: "bra-egy",
    date: "2026-06-07",
    time: "06:00",
    league: "国际友谊",
    home: "巴西",
    away: "埃及",
    homeIcon: "BRA",
    awayIcon: "EGY",
    status: "pending",  // 6/7 完赛·比分未在搜索引擎拉到（数据延迟）
    score: { home: 0, away: 0 },
    prediction: {
      direction: "巴西胜",
      confidence: 4,
      asian: "让球放弃",
      overUnder: "大球",
      goals: "2-3球",
    },
    actual: { directionHit: null, asianHit: null, goalsHit: null, note: '完赛·比分未拉到' },
    liveWarning: "★★★★ FIFA 5 vs 36 · 身价7.8倍 · 维尼修斯+拉菲尼亚领衔 · 反对：内马尔可能不首发",
  },
  {
    id: "arg-hon",
    date: "2026-06-07",
    time: "08:00",
    league: "国际友谊",
    home: "阿根廷",
    away: "洪都拉斯",
    homeIcon: "ARG",
    awayIcon: "HON",
    status: "pending",  // 6/7 完赛·比分未在搜索引擎拉到（数据延迟）
    score: { home: 0, away: 0 },
    prediction: {
      direction: "阿根廷胜",
      confidence: 4,
      asian: "让球放弃",
      overUnder: "大球",
      goals: "2-3球",
    },
    actual: { directionHit: null, asianHit: null, goalsHit: null, note: '完赛·比分未拉到' },
    liveWarning: "★★★★ FIFA 1 vs 76 · 身价21倍 · 卫冕冠军测试 · 反对：无",
  },
];

// 6月7日 战报（5 场 A 级成年男子国际赛 / 副业冷静期到 6/6 晚结束 / 3 场已完赛 2 场数据延迟）
export const report6_7 = {
  date: '2026-06-07',
  matchesTotal: 5,
  matchesFinished: 3,
  matchesPending: 2,
  results: [
    { id: 'usa-ger', actual: '2-1', directionHit: true, asianHit: null, goalsHit: true, note: '✅ 方向+进球全中·哈弗茨2\'+萨内57\'/罗宾逊37\'世界波' },
    { id: 'mkd-bel', actual: '1-1', directionHit: false, asianHit: null, goalsHit: true, note: '❌ 方向反·86分钟阿利奥斯基世界波绝平·补丁L命中应降★★' },
    { id: 'eng-nzl', actual: '1-0', directionHit: true, asianHit: null, goalsHit: false, note: '✅ 方向命中·凯恩45+2\'头球后蹭·但1球未达3-4球上沿' },
  ],
  pending: ['bra-egy', 'arg-hon'],
  summary: '方向 2/3=67% · 让球 0/0 · 进球 2/3=67% · **北马 1-1 比利时补丁L命中** · 巴西/阿根廷完赛比分未拉',
  majorLesson: '**补丁L实战验证**：反对论点≥4条时-1星仍不足·北马vs比4条反对全部命中+比分反向+应直接降★★或放弃',
  focus: '**北马 1-1 比利时 暴露补丁L力度不足**：1-1平局=方向反+进球中·反对论点命中率100%但模型仍3★预测主胜·下一步：4条反对全命中应直接放弃（补丁L强化）',
  activePatches: ['L 反对论点≥3条-2星', 'L 反对论点≥4条直接放弃', 'P 友谊赛3-4球', 'K 跨大洲-1档'],
  fullReportPath: '/skills/football-prediction/outputs/2026-06-07/pred_20260607.md',
};

export const newsItems = [
  { date: '2026-06-07 23:11', source: '网易体育', title: '德国2-1美国 哈弗茨传射+萨内破门 罗宾逊世界波难救主' },
  { date: '2026-06-07 22:54', source: '虎扑', title: '比利时5-0突尼斯 德布劳内+特罗萨德破门 多库两助攻' },
  { date: '2026-06-07 04:30', source: '腾讯', title: '葡萄牙2-1智利 B费世界波 莱奥+罗曼互殴染红' },
  { date: '2026-06-07 04:00', source: '腾讯', title: '英格兰1-0新西兰 凯恩45+2\'头球后蹭破门 恩古莫哈首秀' },
  { date: '2026-06-07 02:45', source: '腾讯', title: '世预赛J组 北马其顿1-1比利时 86分钟阿利奥斯基世界波绝平' },
  { date: '2026-06-06 22:00', source: '直播吧', title: '中国1-1泰国 拜合拉木扳平 阿兰中柱+费南多失点 世预赛C组末轮客战韩国' },
  { date: '2026-06-05 00:01', source: '搜狐', title: '中国vs新加坡6月5日19:30 世预赛后首场热身 邵佳一执教首秀' },
  { date: '2026-06-04 21:00', source: '直播吧', title: '印尼vs阿曼6月5日21:00 世预赛亚洲区 印尼主场必赢' },
  { date: '2026-06-04 19:51', source: '搜狐', title: '西班牙vs伊拉克6月5日03:00 西班牙轮换9主力 亚马尔/尼科伤缺' },
  { date: '2026-06-04 18:00', source: '法国足协', title: '法国vs科特迪瓦6月5日03:10 萨利巴/登贝莱轮休 姆巴佩追平吉鲁57球' },
];

export const execRecord = {
  date: '2026-06-05',
  signals: [
    { id: 'A', match: '印尼 vs 阿曼', pick: '印尼胜', result: '待开赛', outcome: 'pending', note: '世预赛 6月5日 21:00 副业2串1候选' },
    { id: 'B', match: '中国 vs 新加坡', pick: '中国胜', result: '待开赛', outcome: 'pending', note: '友谊赛 6月5日 19:30 副业2串1候选' },
  ],
  totalStake: 200,
  returnAmount: 0,
  pnl: 0,
  roi: 0,
};
