import type { Match, Patch, ModelStat } from './types';

export const matches6_3: Match[] = [
  {
    id: 'col-crc',
    date: '2026-06-02',
    time: '07:00',
    league: '国际友谊',
    home: '哥伦比亚',
    away: '哥斯达黎加',
    homeIcon: 'COL',
    awayIcon: 'CRC',
    status: 'finished',
    score: { home: 3, away: 1 },
    prediction: { direction: '哥伦比亚胜', confidence: 4, asian: '让球放弃', overUnder: '大球', goals: '2-3球' },
    actual: { directionHit: true, asianHit: null, goalsHit: false },
    highlight: true,
    liveWarning: 'FIFA 13 vs 51 · 让球1.75→2球 · 走盘',
  },
  {
    id: 'can-uzb',
    date: '2026-06-02',
    time: '09:00',
    league: '国际友谊',
    home: '加拿大',
    away: '乌兹别克斯坦',
    homeIcon: 'CAN',
    awayIcon: 'UZB',
    status: 'finished',
    score: { home: 2, away: 0 },
    prediction: { direction: '加拿大胜', confidence: 3, asian: '让球放弃', overUnder: '小球', goals: '1-2球' },
    actual: { directionHit: true, asianHit: true, goalsHit: true },
    highlight: true,
    liveWarning: 'FIFA 30 vs 50 · 6月1+2日镜像场景 · 肖穆罗多夫失单刀',
  },
  {
    id: 'ned-sco',
    date: '2026-06-03',
    time: '02:45',
    league: '国际友谊',
    home: '荷兰',
    away: '苏格兰',
    homeIcon: 'NED',
    awayIcon: 'SCO',
    status: 'finished',
    score: { home: 2, away: 2 },
    prediction: { direction: '荷兰胜', confidence: 4, asian: '让球胜', overUnder: '大球', goals: '3-4球' },
    actual: { directionHit: false, asianHit: false, goalsHit: false },
    highlight: true,
    liveWarning: '❌ 德佩 88\' 任意球绝平 · 让球1.5球=输 · 2021年同场地2-2未被识别',
  },
  {
    id: 'ina-yem',
    date: '2026-06-03',
    time: '18:00',
    league: '国际友谊',
    home: '印尼',
    away: '也门',
    homeIcon: 'INA',
    awayIcon: 'YEM',
    status: 'upcoming',
    score: { home: 0, away: 0 },
    prediction: { direction: '印尼胜', confidence: 4, asian: '让球胜', overUnder: '大球', goals: '2-3球' },
    actual: null,
    highlight: true,
    liveWarning: '★★★★ 副业小试水 · 也门10场进7失23 · 2串1待开赛',
  },
  {
    id: 'mar-mad',
    date: '2026-06-03',
    time: '01:00',
    league: '国际友谊',
    home: '摩洛哥',
    away: '马达加斯加',
    homeIcon: 'MAR',
    awayIcon: 'MAD',
    status: 'upcoming',
    score: { home: 0, away: 0 },
    prediction: { direction: '摩洛哥胜', confidence: 4, asian: '让球放弃', overUnder: '大球', goals: '3-4球' },
    actual: null,
    liveWarning: 'FIFA 8 vs 104 · 排名差96位接近100',
  },
  {
    id: 'wal-gha',
    date: '2026-06-03',
    time: '02:45',
    league: '国际友谊',
    home: '威尔士',
    away: '加纳',
    homeIcon: 'WAL',
    awayIcon: 'GHA',
    status: 'upcoming',
    score: { home: 0, away: 0 },
    prediction: { direction: '威尔士胜', confidence: 4, asian: '让球胜', overUnder: '大球', goals: '2-3球' },
    actual: null,
    liveWarning: 'FIFA 37 vs 74 · 加纳5连败全客场 · 跨大洲对决-1档',
  },
];

export const patches: Patch[] = [
  { id: 'P0-1', name: '主队战意强 + 客队已锁定资格', priority: 'P0', category: '基础规则', description: '友谊赛场景下，主队战意强且客队已锁定世界杯资格 → 主动押主队', applied: ['挪威vs瑞典', '印尼vs也门', '威尔士vs加纳'], status: 'active', addedDate: '2026-06-01' },
  { id: 'P0-2', name: '弱弱对决 → 主动放弃', priority: 'P0', category: '基础规则', description: '双方近期胜率均<30% → 触发主动放弃', applied: ['保加利亚vs黑山', '马尔代夫vs阿富汗', '海地vs新西兰'], status: 'active', addedDate: '2026-06-01' },
  { id: 'P0-3', name: '跨大洲对决-1档（真跨大洲）', priority: 'P0', category: '基础规则', description: '欧洲/亚洲/非洲/南美洲之间的真跨大洲对决 → 进球区间-1档', applied: ['威尔士vs加纳', '卡塔尔vs秘鲁', '日本vs委内瑞拉'], status: 'active', addedDate: '2026-06-01' },
  { id: 'P0-4', name: '排名差100+ → 让球主动放弃', priority: 'P0', category: '基础规则', description: 'FIFA排名差距超过100位 → 深度盘口虚高', applied: ['巴西vs巴拿马（让3.5）', '摩洛哥vs马达加斯加（让2-2.5）'], status: 'active', addedDate: '2026-06-01' },
  { id: 'P0-5', name: '双方均无战意 → 放弃', priority: 'P0', category: '基础规则', description: '双方都为练兵性质，无明显战意差异', applied: ['克罗地亚vs比利时'], status: 'active', addedDate: '2026-06-01' },
  { id: 'P1-6', name: 'G · 跨大洲对决精确化', priority: 'P1', category: '实力规则', description: '南美vs中北美 = 近半球对决+1档（不再是跨大洲-1档）', applied: ['哥伦比亚vs哥斯达黎加'], status: 'active', addedDate: '2026-06-02' },
  { id: 'P1-7', name: 'I · 让球放弃精细化', priority: 'P1', category: '实力规则', description: '让球<1球+双方实力接近 → 让球放弃；让球≥2球+主队战意强+核心未缺 → 保留', applied: ['加拿大vs乌兹别克（让0.75放弃）', '哥伦比亚vs哥斯达黎加（让2球放弃）'], status: 'active', addedDate: '2026-06-02' },
  { id: 'P1-8', name: 'T · 资金管理（副业专属）', priority: 'P1', category: '实力规则', description: '副业小试水：单注≤1.5% / 单日≤3场 / 月回撤>15%降级', applied: ['6月3日 2串1 200元套餐'], status: 'active', addedDate: '2026-06-03' },
  { id: 'P2-9', name: 'H · 主队下半场发力', priority: 'P2', category: '修正规则', description: '友谊赛+主队战意强+主力替补登场 → 下半场进球占比>60%', applied: ['德国vs芬兰 4-0', '挪威vs瑞典 3-1', '哥伦比亚vs哥斯达黎加 3-1', '加拿大vs乌兹别克 2-0'], status: 'active', addedDate: '2026-06-02' },
  { id: 'P2-10', name: '8 · 客队进攻效率权重', priority: 'P2', category: '修正规则', description: '客队进攻效率被高估时增加防守数据权重', applied: ['加纳vs威尔士（5连败）', '印尼vs也门（10场进7）'], status: 'active', addedDate: '2026-06-01' },
  { id: 'P2-11', name: 'J · 客队核心决定性瞬间', priority: 'P2', category: '修正规则', description: '客队核心球员（顶级前锋）可能错失单刀或失点 → 影响比赛结果', applied: ['加拿大vs乌兹别克（肖穆罗多夫7\'失单刀）', '威尔士vs加纳（塞梅尼奥）'], status: 'active', addedDate: '2026-06-02' },
  { id: 'P3-12', name: '厚尾场景+1档', priority: 'P3', category: '区间规则', description: '让球≥1.5球时，基准进球区间+1档（避免低估大球）', applied: ['哥伦比亚vs哥斯达黎加（4球）', '摩洛哥vs马达加斯加', '威尔士vs加纳', '荷兰vs苏格兰'], status: 'active', addedDate: '2026-06-01' },
];

export const modelStats: ModelStat[] = [
  { label: '方向准确率', value: '89%', color: 'emerald', trend: 'stable' },
  { label: '让球规避', value: '100%', color: 'gold', trend: 'up' },
  { label: '进球准确率', value: '50%', color: 'amber', trend: 'stable' },
  { label: '主动放弃率', value: '33%', color: 'crimson', trend: 'up' },
];

export const newsItems = [
  { date: '2026-06-03 04:20', source: '体坛+', title: '热身赛-德佩梅开二度 荷兰两度落后2-2绝平苏格兰' },
  { date: '2026-06-03 01:02', source: '懂球帝', title: '科曼:荷兰队状态比欧洲杯时更好' },
  { date: '2026-06-02 09:03', source: '直播吧', title: '友谊赛-加拿大2-0乌兹别克斯坦 肖穆罗多夫失单刀' },
  { date: '2026-06-02 07:31', source: '直播吧', title: '哥伦比亚3-1哥斯达黎加 迪亚斯传射J罗助攻' },
];

export const execRecord = {
  date: '2026-06-03',
  signals: [
    { id: 'A', match: '荷兰 vs 苏格兰', pick: '让球胜', result: '2-2', outcome: 'LOSS', note: '让球1.5球=输' },
    { id: 'B', match: '印尼 vs 也门', pick: '让球胜', result: '待定', outcome: 'pending', note: '2串1已无效' },
  ],
  totalStake: 200,
  returnAmount: 0,
  pnl: -200,
  roi: -100,
};
