import type { Match, Patch, ModelStat } from './types';

// 6月5日 12场 A级成年男子国际赛（12场含 8场预测 + 4场主动放弃）
export const matches6_5: Match[] = [
  {
    id: "esp-irq",
    date: "2026-06-05",
    time: "03:00",
    league: "国际友谊",
    home: "西班牙",
    away: "伊拉克",
    homeIcon: "ESP",
    awayIcon: "IRQ",
    status: "finished",
    score: { home: 1, away: 1 },
    score: { home: 0, away: 0 },
    prediction: {
      direction: "西班牙胜",
      confidence: 4,
      asian: "让球放弃",
      overUnder: "大球",
      goals: "2-3球",
    },
    actual: { directionHit: false, asianHit: null, goalsHit: true },
    highlight: true,
    liveWarning: "★★★★ FIFA #2 vs #57 · 身价60倍 · 西班牙大面积轮换（亚马尔/尼科/拉亚伤缺）· 跨大洲-1档 · 反对：轮换+草皮差 · ❌ 1-1 伊拉克萨阿德32'破门 奥尔莫90'绝平 · 草皮+轮换反对论点全部命中 · 模型应降至★★",
  },
  {
    id: "fra-civ",
    date: "2026-06-05",
    time: "03:10",
    league: "国际友谊",
    home: "法国",
    away: "科特迪瓦",
    homeIcon: "FRA",
    awayIcon: "CIV",
    status: "finished",
    score: { home: 1, away: 2 },
    score: { home: 0, away: 0 },
    prediction: {
      direction: "法国胜",
      confidence: 4,
      asian: "让球降权",
      overUnder: "大球",
      goals: "2-3球",
    },
    actual: { directionHit: false, asianHit: null, goalsHit: true },
    highlight: true,
    liveWarning: "★★★★ FIFA #1 vs #34 · 萨利巴/登贝莱/巴尔科拉轮休 · 姆巴佩追平吉鲁57球 · 跨大洲-1档 · 反对：法科青训内战 · ❌ 1-2 法国队史首次输科特迪瓦 · 谢尔基45'破门后塞拉-杜埃+迪亚洛反超 · 客队3大归化核心决定性",
  },
  {
    id: "ber-biz",
    date: "2026-06-05",
    time: "06:00",
    league: "中北美金杯预选",
    home: "百慕大群岛",
    away: "伯利兹",
    homeIcon: "BER",
    awayIcon: "BIZ",
    status: "upcoming",
    score: { home: 0, away: 0 },
    prediction: {
      direction: "主动放弃",
      confidence: 1,
      asian: "弱弱放弃",
      overUnder: "N/A",
      goals: "N/A",
    },
    actual: null,
    liveWarning: "★ FIFA #168 vs #175 · 排名差7位均150+ · Q2弱弱对决触发",
  },
  {
    id: "cze-gua",
    date: "2026-06-05",
    time: "08:00",
    league: "国际友谊",
    home: "捷克",
    away: "危地马拉",
    homeIcon: "CZE",
    awayIcon: "GUA",
    status: "finished",
    score: { home: 3, away: 1 },
    score: { home: 0, away: 0 },
    prediction: {
      direction: "捷克胜",
      confidence: 4,
      asian: "让球降权",
      overUnder: "大球",
      goals: "2-3球",
    },
    actual: { directionHit: true, asianHit: null, goalsHit: false },
    liveWarning: "★★★★ FIFA #36 vs #107 · 身价15倍 · 跨大洲-1档 · 反对：友谊赛+主队无战意 · ✅方向 4球超出2-3上沿 · 绍切克/赫拉纳克/库切拉进球 · 友谊赛补丁K命中",
  },
  {
    id: "mex-srb",
    date: "2026-06-05",
    time: "10:00",
    league: "国际友谊",
    home: "墨西哥",
    away: "塞尔维亚",
    homeIcon: "MEX",
    awayIcon: "SRB",
    status: "finished",
    score: { home: 5, away: 1 },
    score: { home: 0, away: 0 },
    prediction: {
      direction: "墨西哥胜",
      confidence: 4,
      asian: "让球降权",
      overUnder: "大球",
      goals: "2-3球",
    },
    actual: { directionHit: true, asianHit: null, goalsHit: false },
    liveWarning: "★★★★ FIFA #15 vs #33 · 身价2.5倍 · 核心伤缺（阿尔瓦雷斯/蒙特斯/希门尼斯）· 跨大洲-1档 · ✅方向 6球远超2-3 · 阿尔瓦雷斯梅开二度 · 跨大洲友谊赛补丁K命中",
  },
  {
    id: "jam-rsa",
    date: "2026-06-05",
    time: "19:00",
    league: "国际友谊",
    home: "牙买加",
    away: "南非",
    homeIcon: "JAM",
    awayIcon: "RSA",
    status: "pending",
    score: { home: 0, away: 0 },
    prediction: {
      direction: "主动放弃",
      confidence: 2,
      asian: "弱弱边界",
      overUnder: "N/A",
      goals: "N/A",
    },
    actual: null,
    liveWarning: "★★ FIFA #64 vs #58 · 跨大洲友谊赛 · 战意不明",
  },
  {
    id: "sgp-chn",
    date: "2026-06-05",
    time: "19:30",
    league: "国际友谊（备战亚洲杯）",
    home: "新加坡",
    away: "中国",
    homeIcon: "SGP",
    awayIcon: "CHN",
    status: "finished",
    score: { home: 1, away: 2 },
    score: { home: 0, away: 0 },
    prediction: {
      direction: "中国胜",
      confidence: 3,
      asian: "让球放弃",
      overUnder: "小球",
      goals: "1-2球",
    },
    actual: { directionHit: true, asianHit: null, goalsHit: false },
    highlight: true,
    liveWarning: "★★★ FIFA #147 vs #94 · 武磊百场纪念仅踢几分钟 · 朱辰杰/蒋光太/林良铭伤停 · 反对：伤停+客场+友谊赛3重不利 · 邵佳一新教练 · ✅方向 3球超出1-2上沿 · 张玉宁点球+王钰栋 · 邵佳一执教首秀胜",
  },
  {
    id: "hkg-mng",
    date: "2026-06-05",
    time: "20:00",
    league: "国际赛",
    home: "中国香港",
    away: "蒙古",
    homeIcon: "HKG",
    awayIcon: "MNG",
    status: "pending",
    score: { home: 0, away: 0 },
    prediction: {
      direction: "主动放弃",
      confidence: 1,
      asian: "弱弱放弃",
      overUnder: "N/A",
      goals: "N/A",
    },
    actual: null,
    liveWarning: "★ FIFA #148 vs #182 · 排名均150+ · Q2弱弱对决",
  },
  {
    id: "ner-mtn",
    date: "2026-06-05",
    time: "20:00",
    league: "国际赛",
    home: "尼日尔",
    away: "毛里塔尼亚",
    homeIcon: "NER",
    awayIcon: "MTN",
    status: "pending",
    score: { home: 0, away: 0 },
    prediction: {
      direction: "主动放弃",
      confidence: 1,
      asian: "弱弱放弃",
      overUnder: "N/A",
      goals: "N/A",
    },
    actual: null,
    liveWarning: "★ FIFA #120 vs #105 · 非洲内战 · 数据稀薄",
  },
  {
    id: "tha-kuw",
    date: "2026-06-05",
    time: "20:30",
    league: "国际友谊",
    home: "泰国",
    away: "科威特",
    homeIcon: "THA",
    awayIcon: "KUW",
    status: "finished",
    score: { home: 2, away: 2 },
    score: { home: 0, away: 0 },
    prediction: {
      direction: "泰国胜",
      confidence: 3,
      asian: "让球放弃",
      overUnder: "大球",
      goals: "2-3球",
    },
    actual: { directionHit: false, asianHit: null, goalsHit: false },
    liveWarning: "★★★ FIFA #82 vs #126 · 身价2.5倍 · 亚洲内战 · 反对：友谊赛双方无战意 · ❌ 2-0领先被89'补时绝平 · 完美验证友谊赛补丁K · 应在2-0 60分钟后直接放弃",
  },
  {
    id: "ina-oma",
    date: "2026-06-05",
    time: "21:00",
    league: "世预赛亚洲区",
    home: "印尼",
    away: "阿曼",
    homeIcon: "INA",
    awayIcon: "OMA",
    status: "pending",
    score: { home: 0, away: 0 },
    prediction: {
      direction: "印尼胜",
      confidence: 4,
      asian: "让球降权",
      overUnder: "小球",
      goals: "1-2球",
    },
    actual: null,
    highlight: true,
    liveWarning: "★★★★ FIFA #123 vs #78 · 身价2.6倍 · 世预赛≠友谊赛 · 门将佩斯+核心费迪南停赛 · 主场必赢战意双高",
  },
  {
    id: "tjk-ind",
    date: "2026-06-05",
    time: "23:00",
    league: "国际赛",
    home: "塔吉克斯坦",
    away: "印度",
    homeIcon: "TJK",
    awayIcon: "IND",
    status: "pending",
    score: { home: 0, away: 0 },
    prediction: {
      direction: "主动放弃",
      confidence: 1,
      asian: "弱弱放弃",
      overUnder: "N/A",
      goals: "N/A",
    },
    actual: null,
    liveWarning: "★ FIFA #108 vs #124 · 亚洲内战 · 数据稀薄",
  },
];

// 历史：6月2-3日 已完赛 4场
export const matches6_3: Match[] = [
  {
    id: "col-crc",
    date: "2026-06-02",
    time: "07:00",
    league: "国际友谊",
    home: "哥伦比亚",
    away: "哥斯达黎加",
    homeIcon: "COL",
    awayIcon: "CRC",
    status: "finished",
    score: { home: 3, away: 1 },
    prediction: {
      direction: "哥伦比亚胜",
      confidence: 4,
      asian: "让球放弃",
      overUnder: "大球",
      goals: "2-3球",
    },
    actual: { directionHit: true, asianHit: null, goalsHit: false },
    highlight: true,
    liveWarning: "FIFA 13 vs 51 · 让球1.75→2球 · 走盘",
  },
  {
    id: "can-uzb",
    date: "2026-06-02",
    time: "09:00",
    league: "国际友谊",
    home: "加拿大",
    away: "乌兹别克斯坦",
    homeIcon: "CAN",
    awayIcon: "UZB",
    status: "finished",
    score: { home: 2, away: 0 },
    prediction: {
      direction: "加拿大胜",
      confidence: 3,
      asian: "让球放弃",
      overUnder: "小球",
      goals: "1-2球",
    },
    actual: { directionHit: true, asianHit: true, goalsHit: true },
    highlight: true,
    liveWarning: "FIFA 30 vs 50 · 6月1+2日镜像场景 · 肖穆罗多夫失单刀",
  },
  {
    id: "ned-sco",
    date: "2026-06-03",
    time: "02:45",
    league: "国际友谊",
    home: "荷兰",
    away: "苏格兰",
    homeIcon: "NED",
    awayIcon: "SCO",
    status: "finished",
    score: { home: 2, away: 2 },
    prediction: {
      direction: "荷兰胜",
      confidence: 4,
      asian: "让球胜",
      overUnder: "大球",
      goals: "3-4球",
    },
    actual: { directionHit: false, asianHit: false, goalsHit: false },
    highlight: true,
    liveWarning: "❌ 德佩88'任意球绝平 · 让球1.5球=输 · 2021年同场地2-2未被识别",
  },
];

export const patches: Patch[] = [
  { id: "Q6", name: "Q6 · 赛事真实性验证（地基）", priority: "P0", category: "基础规则", description: "每场预测前强制 6 项验证：3源赛程+成年男子 A级+12-72h+场地+近况。不通过 = 直接放弃", applied: ["6月5日 印尼vs中国 修正为 印尼vs阿曼", "6月3日 印尼vs也门 识别为赛事不存在"], status: "active", addedDate: "2026-06-04" },
  { id: "P0-1", name: "主队战意强 + 客队已锁定资格", priority: "P0", category: "基础规则", description: "友谊赛场景下，主队战意强且客队已锁定世界杯资格 → 主动押主队", applied: ["挪威vs瑞典", "印尼vs也门", "威尔士vs加纳"], status: "active", addedDate: "2026-06-01" },
  { id: "P0-2", name: "弱弱对决 → 主动放弃", priority: "P0", category: "基础规则", description: "双方近期胜率均<30% → 触发主动放弃", applied: ["保加利亚vs黑山", "马尔代夫vs阿富汗", "海地vs新西兰", "6月5日 百慕大vs伯利兹/中国香港vs蒙古/尼日尔vs毛里塔尼亚/塔吉克vs印度"], status: "active", addedDate: "2026-06-01" },
  { id: "P0-3", name: "跨大洲对决-1档（真跨大洲）", priority: "P0", category: "基础规则", description: "欧洲/亚洲/非洲/南美洲之间的真跨大洲对决 → 进球区间-1档", applied: ["威尔士vs加纳", "卡塔尔vs秘鲁", "日本vs委内瑞拉", "6月5日 西班牙vs伊拉克/法国vs科特迪瓦/捷克vs危地马拉/墨西哥vs塞尔维亚"], status: "active", addedDate: "2026-06-01" },
  { id: "P0-4", name: "排名差100+ → 让球主动放弃", priority: "P0", category: "基础规则", description: "FIFA排名差距超过100位 → 深度盘口虚高", applied: ["巴西vs巴拿马（让3.5）", "摩洛哥vs马达加斯加（让2-2.5）"], status: "active", addedDate: "2026-06-01" },
  { id: "P0-5", name: "双方均无战意 → 放弃", priority: "P0", category: "基础规则", description: "双方都为练兵性质，无明显战意差异", applied: ["克罗地亚vs比利时", "6月5日 牙买加vs南非"], status: "active", addedDate: "2026-06-01" },
  { id: "P1-6", name: "G · 跨大洲对决精确化", priority: "P1", category: "实力规则", description: "南美vs中北美 = 近半球对决+1档（不再是跨大洲-1档）", applied: ["哥伦比亚vs哥斯达黎加"], status: "active", addedDate: "2026-06-02" },
  { id: "P1-7", name: "I · 让球放弃精细化", priority: "P1", category: "实力规则", description: "让球<1球+双方实力接近 → 让球放弃；让球≥2球+主队战意强+核心未缺 → 保留", applied: ["加拿大vs乌兹别克（让0.75放弃）", "哥伦比亚vs哥斯达黎加（让2球放弃）"], status: "active", addedDate: "2026-06-02" },
  { id: "P1-8", name: "T · 资金管理（副业专属）", priority: "P1", category: "实力规则", description: "副业小试水：单注≤1.5% / 单日≤3场 / 月回撤>15%降级 / 每日1注2串1=200元", applied: ["6月3日 2串1 200元套餐（失败）", "6月5日 2串1 候选 A 印尼×中国"], status: "active", addedDate: "2026-06-03" },
  { id: "P2-9", name: "H · 主队下半场发力", priority: "P2", category: "修正规则", description: "友谊赛+主队战意强+主力替补登场 → 下半场进球占比>60%", applied: ["德国vs芬兰 4-0", "挪威vs瑞典 3-1", "哥伦比亚vs哥斯达黎加 3-1", "加拿大vs乌兹别克 2-0"], status: "active", addedDate: "2026-06-02" },
  { id: "P2-10", name: "8 · 客队进攻效率权重", priority: "P2", category: "修正规则", description: "客队进攻效率被高估时增加防守数据权重", applied: ["加纳vs威尔士（5连败）", "印尼vs也门（10场进7）"], status: "active", addedDate: "2026-06-01" },
  { id: "P2-11", name: "J · 客队核心决定性瞬间", priority: "P2", category: "修正规则", description: "客队核心球员（顶级前锋）可能错失单刀或失点 → 影响比赛结果", applied: ["加拿大vs乌兹别克（肖穆罗多夫7'失单刀）", "威尔士vs加纳（塞梅尼奥）", "6月5日 科特迪瓦（佩佩/迪亚洛）"], status: "active", addedDate: "2026-06-02" },
  { id: "P2-12", name: "K · 友谊赛降权（6月5日新增）", priority: "P2", category: "修正规则", description: "友谊赛中 身价差距+历史交锋+核心未缺 等信号降级处理。轮换强队 = 有包袱+无所求弱队反压制", applied: ["6月3日 美国vs塞内加尔（友谊赛）", "6月3日 荷兰vs苏格兰（友谊赛）", "6月5日 西班牙vs伊拉克（轮换）", "6月5日 法国vs科特迪瓦（轮换）", "6月5日 新加坡vs中国（伤停）"], status: "active", addedDate: "2026-06-03" },
  { id: "P3-13", name: "厚尾场景+1档", priority: "P3", category: "区间规则", description: "让球≥1.5球时，基准进球区间+1档（避免低估大球）", applied: ["哥伦比亚vs哥斯达黎加（4球）", "摩洛哥vs马达加斯加", "威尔士vs加纳", "荷兰vs苏格兰"], status: "active", addedDate: "2026-06-01" },
];

export const modelStats: ModelStat[] = [
  { label: '方向准确率', value: '73%', color: 'emerald', trend: 'down' },
  { label: '让球规避', value: '100%', color: 'gold', trend: 'up' },
  { label: '进球准确率', value: '27%', color: 'amber', trend: 'down' },
  { label: '主动放弃率', value: '27%', color: 'crimson', trend: 'up' },
];

// 6月5日 战报（11 场 A 级成年男子国际赛 / 6 场已完赛 5 场数据延迟）
export const report6_5 = {
  date: '2026-06-05',
  matchesTotal: 11,
  matchesFinished: 6,
  matchesPending: 5,
  results: [
    { id: 'esp-irq', actual: '1-1', directionHit: false, goalsHit: true, note: '草皮+轮换反对论点全命中' },
    { id: 'fra-civ', actual: '1-2', directionHit: false, goalsHit: true, note: '法国队史首负科特迪瓦' },
    { id: 'cze-gua', actual: '3-1', directionHit: true, goalsHit: false, note: '方向对 4球超 2-3' },
    { id: 'mex-srb', actual: '5-1', directionHit: true, goalsHit: false, note: '方向对 6球远超' },
    { id: 'sgp-chn', actual: '1-2', directionHit: true, goalsHit: false, note: '方向对 3球超 1-2' },
    { id: 'tha-kuw', actual: '2-2', directionHit: false, goalsHit: false, note: '2-0 领先 89'补时被逼平' },
  ],
  summary: '方向 3/6=50% · 让球 0/6=0% · 进球 2/6=33% · 主动放弃 3/11=27%',
  lessons: [
    '补丁L 反对论点强制扣星（≥1条-1星 ≥2条-2星 ≥3条放弃）',
    '补丁K 升级 友谊赛细分（2-0 60 分钟+/客队3+五大核心/同大洲必放弃）',
    '补丁M 中国 6 月友谊赛 3-4 球区间',
    '补丁N 法国 vs 非洲归化强队 必放弃友谊赛方向',
    '补丁O 墨西哥友谊赛 3-5 球区间',
    '补丁P 友谊赛默认 3-4 球（首日 67% 3 球+ 概率）',
  ],
  fullReportPath: '/skills/football-prediction/outputs/2026-06-05/review_20260605.md',
};

export const newsItems = [
  { date: '2026-06-05 00:01', source: '搜狐', title: '中国vs新加坡6月5日19:30 世预赛后首场热身 邵佳一执教首秀' },
  { date: '2026-06-04 21:00', source: '直播吧', title: '印尼vs阿曼6月5日21:00 世预赛亚洲区 印尼主场必赢' },
  { date: '2026-06-04 19:51', source: '搜狐', title: '西班牙vs伊拉克6月5日03:00 西班牙轮换9主力 亚马尔/尼科伤缺' },
  { date: '2026-06-04 18:00', source: '法国足协', title: '法国vs科特迪瓦6月5日03:10 萨利巴/登贝莱轮休 姆巴佩追平吉鲁57球' },
  { date: '2026-06-03 04:20', source: '体坛+', title: '热身赛-德佩梅开二度 荷兰两度落后2-2绝平苏格兰' },
  { date: '2026-06-02 09:03', source: '直播吧', title: '友谊赛-加拿大2-0乌兹别克斯坦 肖穆罗多夫失单刀' },
];

export const execRecord = {
  date: '2026-06-05',
  signals: [
    { id: 'A', match: '印尼 vs 阿曼', pick: '印尼胜', result: '待开赛', outcome: 'pending', note: '世预赛 6月5日 21:00 副业2串1候选' },
    { id: 'B', match: '中国 vs 新加坡', pick: '中国胜', result: '待开赛', outcome: 'pending', note: '友谊赛 6月5日 19:30 副业2串1候选' },
  ],
  totalStake: 200,
  returnAmount: 0,
  pnl: 0,
  roi: 0,
};
